name: main

on:
  push:
    paths:
      - 'latest-tag/*'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: ./${{ github.event.repository.name }}

      - name: Check repo
        uses: actions/checkout@v2
        with:
          repository: smithy9901/build_peervpn
          path: ./build_peervpn

      - name: decode secret key
        run: echo -n "${{ secrets.PRIVATE_KEY_ASC }}" | base64 --decode > ./${{ github.event.repository.name }}/private-key.asc

      - name: Build ppa repo
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./${{ github.event.repository.name }}/Dockerfile
          outputs: type=local,dest=./${{ github.event.repository.name }}/ubuntu
          build-args: "REPO_NAME=${{ github.event.repository.name }}"
          push: false

      - name: Check for modified files
        id: git-check
        run: |
          cd  ./${{ github.event.repository.name }}
          echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")

      - name: Commit ppa file
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.git-check.outputs.modified == 'true'
        with:
          commit_message: New package version
          repository: ./${{ github.event.repository.name }}
          file_pattern: ./ubuntu/*
